# Generated by Django 5.0.3 on 2024-03-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='course/teacher')),
                ('link_twitter', models.URLField()),
                ('link_facebook', models.URLField()),
                ('link_in', models.URLField()),
                ('create_date', models.DateField()),
            ],
        ),
    ]
