# Generated by Django 5.0.3 on 2024-03-22 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='Speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.position'),
            preserve_default=False,
        ),
    ]
