# Generated by Django 5.0.3 on 2024-03-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_position_teacher_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='link_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='link_in',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='link_twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
